sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r test-requirements.txt
  - pip install -e .
  - pip install codecov

script: python -m pytest --verbose tests

after_success:
  - codecov
